Add CIP cartridge JSON data
ammolytics/cartridges pull request #8
Opened 2018-08-23 14:46 UTC by GAO8A

Added JSON data for CIP cartridges.

- Names contain comma decimal separator. Should we standardize to dot?

- `data/rifle/cip.json` contains combined data of:

1. Rimless cartridges 
2. Rimmed cartridges 
3. Magnum cartridges

It contains escape character `\"` (eg. `450 N.E. 3\" 1/4"`) but also `“` (eg. `475 N° 2 N.E. 3“1/2 Jeffery`). Should we standardize?

- CIP's classification is more specific than the current 4 types of data, but for less conventional/common cartridge types. Should we expand?

Thanks!

2018-08-24 07:52 UTC, erichiggins commented
Does CIP offer any explanation for the discrepancies in the different style of quotation characters?  If not, I'd prefer to standardize, yes.

Are the rimless/rimmed/magnum the other types that they support beyond rifle, pistol, and shotshell?

2018-08-27 15:23 UTC, erichiggins requested changes
Looks pretty good overall, just a few changes suggested. Once you get the final names for all of the CIP cartridges, they should also be included in `cartridges.json` and `cartridges.csv`.

2018-08-27 15:23 UTC, erichiggins commented on data/pistol/cip.json
> +    "357 Magnum (carb)": {},
Do you happen to know what `(carb)` stands for?

2018-08-27 15:23 UTC, erichiggins commented on data/rifle/README.md
> +##CIP
You need a space between the `##` and title for the Markdown to style it correctly (e.g. `## CIP`).  You can [preview it here](https://github.com/ammolytics/cartridges/blob/d36f6595dd861c16b46e0dad672d0983128da2d7/data/rifle/README.md).

2018-08-27 15:23 UTC, erichiggins commented on data/pistol/README.md
> +7 mm Penna L
Does CIP intentionally separate the unit from the caliber with a space in the official cartridge name? `7 mm` vs `7mm`?

2018-08-27 15:23 UTC, erichiggins commented on data/pistol/README.md
> +22 Rem.Jet Mag.
I probably neglected to state it in the README, but the list of names should be the official long-form cartridge name (e.g.  `Remington Magnum` instead of `Rem Mag`).  There's space to store shorter alternative names within the CSV and JSON once we get to that point.

2018-08-27 19:58 UTC, GAO8A commented on data/pistol/cip.json
> +    "357 Magnum (carb)": {},
Not sure after some digging. Dimensions appear to be nearly identical, carbine perhaps?

2018-08-27 19:59 UTC, GAO8A commented on data/rifle/README.md
> +##CIP
👍

2018-08-27 20:00 UTC, GAO8A commented on data/pistol/README.md
> +7 mm Penna L
It appears so, should there be no space?

2018-08-30 22:38 UTC, erichiggins commented
GitHub indicates the following when I tried to view `cartridges.csv`

> We can make this file beautiful and searchable if this error is corrected: Missing or stray quote in line 593

2018-08-31 05:26 UTC, erichiggins approved these changes

2018-08-31 05:27 UTC, merged